#!/usr/bin/env bash
cmd_exists() { command -v $1 &>/dev/null ; }

if ! cmd_exists git; then
 echo "You need git for this..." && exit 1
fi

CWD="$(pwd)"
cd "$HOME/.conf_files"
case $1 in
  fpush)
    git_fast_push
  ;;
  *)
    git $@
  ;;
esac

cd "$CWD"
