#!/usr/bin/env bash

prog_exists() {
	which "$1" &>/dev/null 2>&1;
}

prog_exists apt || { echo "Apt not found. This program is only for Debian."; exit 1; }

if [ "$(id -u)" != "0" ]; then
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
	sudo $DIR/apt_autopurge
else
	dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge
fi

