#!/usr/bin/env bash
# Conectar claro usb red.
mmcli -S && \
mmcli -L && \
read -p "Modem index> " m && \
mmcli -m $m --simple-connect="apn=ba.amx,user=ppp@A1plus.at,password=clarogprs999" && \
nmtui

