#!/usr/bin/env bash
COMPILER=$(which mono-csc)
leave=0
ucode=$(gen_ucode)
tmp_file_source="/tmp/${ucode}.cs"
tmp_file_bin="/tmp/${ucode}.exe"

echo -n "/Td6WFoAAATm1rRGBMDPAcQCIQEcAAAAAAAAABP7AGLgAUMAx10AOpzJVotO+mpQsfTdU7bFTYl3nFKBnmE+mj+pkfJpVCyaZwVpZF4oRMx9fWCIs2wv/F2Mvy3nsAj5YQXNRV5QoSxPWToe2Xjs1NfhK0G4lDJJjdnj7Jo8X2190moGABvvHE6NDm5qcZlnz54QLzwTb37luVXf5TDzHaYh+YMEsJlbbCZd73kmijzeeSM2NFTy10w56DcFvYEImmGWKGEavd7+4ZCKiqUJtfZF+z1ytnEJWLWS8hu9mrsVM8bLZxz80mFxNK1V7QAAzLmeHAICZ/8AAesBxAIAABO7HXixxGf7AgAAAAAEWVo=" | base64 -d | xz -d -k -c -q - > $tmp_file_source

while [ "$leave" == "0" ]; do
	$EDITOR $tmp_file_source
	$COMPILER $tmp_file_source -out:$tmp_file_bin && $tmp_file_bin
	echo "Program returned code $?"
	echo "	1) Edit source ; recompile & run"
	echo "	2) Copy source to clipboard & leave"
	echo "	3) Just leave"
	read o
	if [ "$o" == "1" ]; then
		leave=0
	elif [ "$o" == "2" ]; then
		cat $tmp_file_source | xsel -b
		leave=1
	elif [ "$o" == "3" ]; then
		leave=1
	fi
done

rm -fv $tmp_file_source
rm -fv $tmp_file_bin
