#!/bin/bash
CXXFLAGS="-O2 -march=native -mtune=native"

leave=0
ucode=$(gen_ucode)
tmp_file_source="/tmp/${ucode}.cc"
tmp_file_bin="/tmp/${ucode}.bin"

echo -n "/Td6WFoAAATm1rRGBMBvcCEBHAAAAAAAAAAAAH7iw6PgAG8AZ10AEZpJxkcPE6IAdzsc64tkExchzZrFMr7V2VRT0st/Q53j2NngrE70S1fpc11jpblHnOy4mOhNGnGHOT+hWMmtWWmQXzJMNV1FBCVZVgFi9knk2lzVQVvni4K1UDbTHZw++kywr4HBgAAAKdOUaTtG9RMAAYsBcAAAAOq5feGxxGf7AgAAAAAEWVo=" \
| base64 -d | xz -d -k -c -q - > $tmp_file_source

while [ "$leave" == "0" ]; do
	$EDITOR $tmp_file_source
	g++ $CXXFLAGS $tmp_file_source -o $tmp_file_bin
	$tmp_file_bin
	echo "Program returned code $?"
	echo "	1) Edit source ; recompile & run"
	echo "	2) Copy source to clipboard & leave"
	echo "	3) Just leave"
	read o
	if [ "$o" == "1" ]; then
		leave=0
	elif [ "$o" == "2" ]; then
		cat $tmp_file_source | xsel -b
		leave=1
	elif [ "$o" == "3" ]; then
		leave=1
	fi
done

rm -fv $tmp_file_source
rm -fv $tmp_file_bin
