#!/usr/bin/env bash

read -r -p "This script will change the permissions of the current folder. You might need sudo. - Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	find . -type f -exec chmod 644 {} + -o -type d -exec chmod 755 {} +
        ;;
    *)
    	exit 1;
        ;;
esac
