#!/usr/bin/env bash

read -r -p "This script will change the permissions of the current folder. You might need sudo. - Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	find . -type d -print0 | xargs -0 chmod 755  
	find . -type f -print0 | xargs -0 chmod 644
        ;;
    *)
    	exit 1;
        ;;
esac


