#!/usr/bin/env bash
# Lucie - 20221031 - The idea of this script is to create a similar code like an uuid

time=$(date +%s)
macs=$(cat /sys/class/net/*/address)
seed=$(head -c 100 /dev/random | base64)

echo $seed$macs$time | sha1sum | cut -d" " -f1
