#!/usr/bin/env sh

SOURCE_DIR="$HOME/.conf_files/data/direnv_node_npm"

cp -v ${SOURCE_DIR}/flake.nix flake.nix
cp -v ${SOURCE_DIR}/envrc .envrc

if test -d ".git"; then
  echo "Git detected, stagging files"
  git add flake.nix
  git add .envrc

  echo "Appening gitignore"
  if test -f ".gitignore"; then
    echo >> .gitignore
  fi

  cat ${SOURCE_DIR}/gitignore >> .gitignore
fi
