#!/usr/bin/env sh

DATA_DIR="$HOME/.conf_files/data/direnv/$@"

if [ ! -d $DATA_DIR ]; then
  echo "data directory: $DATA_DIR does not exists"
  exit 1
fi

cp -v ${DATA_DIR}/flake.nix flake.nix
test -f "${DATA_DIR}/envrc" && cp -v ${DATA_DIR}/envrc .envrc

if test -d ".git"; then
  echo "Git detected, stagging files"
  git add flake.nix
  test -f "${DATA_DIR}/envrc" && git add .envrc

  if test -f "${DATA_DIR}/gitignore"; then
    test -f ".gitignore" && echo >> .gitignore
    cat ${DATA_DIR}/gitignore >> .gitignore
    git add .gitignore
  fi
fi

direnv allow
