#!/usr/bin/env sh

DATA_DIR="$HOME/.conf_files/data/direnv/$@"

if [ ! -d $DATA_DIR ]; then
  echo "data directory: $DATA_DIR does not exists"
  exit 1
fi

cp -v ${DATA_DIR}/flake.nix flake.nix
cp -v ${DATA_DIR}/envrc .envrc

if test -d ".git"; then
  echo "Git detected, stagging files"
  git add .envrc
  git add flake.nix

  test -f ".gitignore" && echo >> .gitignore

  echo "# nix + direnv" >> .gitignore
  echo ".direnv" >> .gitiginore

  if test -f "${DATA_DIR}/gitignore"; then
    cat ${DATA_DIR}/gitignore >> .gitignore
  fi

  git add .gitignore
fi

direnv allow
