#!/bin/bash
VM_FOLDER="$HOME/VM"

if [ "$#" -ne 1 ]; then
	if [ -d "$VM_FOLDER/$(basename $(pwd))" ]; then
		$0 "$(basename $(pwd))"
		exit 0
	else
		echo "Usage: qemu-run <vm_name>"
		exit 1
	fi
fi

if [ ! -d "$VM_FOLDER/$1" ]; then
	echo "The vm does not exists."
	exit 1
fi

VM_FOLDER="$VM_FOLDER/$1"
QEMU_CPU=""
QEMU_BOOT_ORDER=""
QEMU_PROGRAM="qemu-system-x86_64"
QEMU_RAM="-m 2G"
QEMU_HDD=""
QEMU_CDROM=""
QEMU_KVM="--enable-kvm"
QEMU_VGA="-vga std"
QEMU_PORT_FWD=""

[ -f "$VM_FOLDER/cfg_boot_order" ] && QEMU_BOOT_ORDER="-boot order=$(cat $VM_FOLDER/cfg_boot_order | head -n 1)"
[ -f "$VM_FOLDER/cfg_x32" ] && QEMU_PROGRAM="qemu-system-i386"
[ -f "$VM_FOLDER/cfg_ram" ] && QEMU_RAM="$(cat $VM_FOLDER/config_ram | head -n 1)"
[ -f "$VM_FOLDER/cfg_no_kvm" ] && QEMU_KVM=""
[ -f "$VM_FOLDER/disk.qcow2" ] && QEMU_HDD="-drive file=$VM_FOLDER/disk.qcow2,format=qcow2"
[ -f "$VM_FOLDER/cdrom.iso" ] && QEMU_CDROM="-cdrom $VM_FOLDER/cdrom.iso"
[ -f "$VM_FOLDER/cfg_vga" ] && QEMU_VGA="$(cat $VM_FOLDER/cfg_vga | head -n 1)"

if [ -f "$VM_FOLDER/cfg_portfwd" ]; then
	for line in $(cat "$VM_FOLDER/cfg_portfwd"); do
		if [ "$line" != "" ]; then
			TMP1="${TMP1},hostfwd=tcp::${line}"
		fi
	done
	QEMU_PORT_FWD=$TMP1
fi

SDL_VIDEO_X11_DGAMOUSE=0 $QEMU_PROGRAM $QEMU_KVM $QEMU_RAM \
-object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 \
-usb -device usb-tablet \
$QEMU_VGA -display sdl,gl=on -monitor stdio \
-nic user$QEMU_PORT_FWD $QEMU_HDD $QEMU_CDROM $QEMU_BOOT_ORDER
