#!/usr/bin/env bash
# This script is for restarting specific processes related to network.

_restart_sv() {
	for s in $@; do
		sudo systemctl restart $s
	done
}

_restart_sv systemd-resolved NetworkManager tailscaled

