#!/usr/bin/env bash
# Lucie - 20221031 - This script is for restarting specific processes related to network.

_res() {
	for s in $@; do
		sudo systemctl restart $s
	done
}

_res dhcpcd@enp5s0 dnscrypt-proxy unbound
