#!/usr/bin/env bash

DEST_DIR="luxlibre:/home/luc/srv/files/scrot/"
URL_PREFIX="https://file.lucdev.net/scrot"
FILENAME=$(scrot '%Y-%m-%d_$wx$h_scrot.png' -e 'echo $f')

scp ./$FILENAME $DEST_DIR && \
rm -v ./$FILENAME && \
echo "${URL_PREFIX}/$FILENAME" | xsel -b


