#!/usr/bin/env bash
# usage: tmux-at [session_name]

SESSION_NAME=${1:-$(basename $(pwd))}

if tmux has-session -t "$SESSION_NAME" >/dev/null 2>&1; then
	# session exists
	tmux attach -t "$SESSION_NAME"
else
	# create session
	tmux new -s "$SESSION_NAME"
fi
